theme: jekyll-theme-cayman
title: Haoling's reading list
description: Thanks to all my teachers, mentors and leaders in my journey exploring the world. 
show_downloads: false

background_image: "/assets/images/rice.jpg"
include: ["_posts"]
